default:
  image: ynotbs/nextflow:latest

variables:
  LINT_OUTPUT: "lint_output.json"
  PREVIOUS_LINT_OUTPUT: "previous_lint_output.json"

stages:
  - lint
  - test

flake8:
  stage: lint
  script:
    - python --version
    - pip install flake8
    - flake8 --config custom-flake8.conf /auto-phylo/Python/retrieve_seqs.py || true
    - flake8 --config custom-flake8.conf /auto-phylo/Python/tree_generator.py || true
    - flake8 . --format=json --output-file=$LINT_OUTPUT || true
  artifacts:
    paths:
      - $LINT_OUTPUT
    when: always
    expire_in: 1 day